/**
 * Define storage types
 */
const storageType = {
	VENUE: 'VENUE',
	LANGUAGE: 'LANGUAGE',
	TRANSLATIONS: 'TRANSLATIONS',
	ACCESS_TOKEN: 'ACCESS_TOKEN',
	USER_TOKEN: 'USER_TOKEN',
	AUTH_USER: 'AUTH_USER',
	USER_ROLE_ID: 'USER_ROLE_ID',
	ACTIVE_MENU_ID: 'ACTIVE_MENU_ID',
	CATEGORY_ID: 'CATEGORY_ID',
	CATEGORY_ARR: 'CATEGORY_ARR',
	CART_ITEMS: 'CART_ITEMS',
	CART_ITEMS_QUICKBILL: 'CART_ITEMS_QUICKBILL',
	CART_ITEMS_DINEIN: 'CART_ITEMS_DINEIN',
	CART_ITEMS_TAKEAWAY: 'CART_ITEMS_TAKEAWAY',
	CART_ITEMS_BUFFET: 'CART_ITEMS_BUFFET',
	ACTIVE_ORDER_NO: 'ACTIVE_ORDER_NO',
	NEW_ORDERS: 'NEW_ORDERS',
	CUSTOMER_ID: 'CUSTOMER_ID',
	VENUE_ID: 'VENUE_ID',
	PlACE_ID: 'PlACE_ID',
	TABLE_ID: 'TABLE_ID',
	CUSTOMER_INFO: 'CUSTOMER_INFO',
	APP_VERSION: 'APP_VERSION',
};
export default storageType;
